name: Treinamento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/setup-node@v2.1.4
       with:
        node-version: 6
        
     - name: Task 1 Exemplo
       run: echo 'Task 1 Exeplo'
##################################################################################################
##################################################################################################
 

